### PR TITLE
non-deprecated new libarchive API

### PR DESCRIPTION
**Pull request by iMokhles**

### CODE REVIEW

**Comment by EthanArbuckle** [comment]
i dont always PR, but when i do, I only change 1 line

**Comment by iMokhles** [comment]
Where is the TODO list to change more than one line ?

**Comment by EthanArbuckle** [comment]
english check please

**Comment by alexzielenski** [comment]
Have you tested this?

**Comment by iMokhles** [comment]
على ما اعتقد انه مش مهم الكلام ده
Ethan 
learn's arabic to understand 
CLOSED

**Comment by mstg** [comment]
Thanks! Tested.

**Pull request merged**
